# Generated by Django 5.2.17 on 2026-10-03 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_companypermission_memberpermission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('supplier_found', 'Supplier Found'), ('lead_updated', 'Lead Updated'), ('requirement_created', 'Requirement Created'), ('product_created', 'Product Created'), ('member_invited', 'Member Invited'), ('plan_upgraded', 'Plan Upgraded'), ('inquiry_sent', 'Inquiry Sent'), ('search_started', 'Search Started')], default='supplier_found', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon_type', models.CharField(default='building', max_length=50)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='companies.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
