# Generated by Django 5.2.17 on 2026-10-08 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_companyrole_companymember_custom_role_rolepermission_and_more'),
        ('dashboard', '0002_supportticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('proposal_sent', 'Proposal / RFQ Sent'), ('inquiry_reply', 'Inquiry Follow-up / Reply'), ('quote_received', 'Quote Recorded / Received'), ('status_changed', 'Stage Transition'), ('deal_won', 'Deal Won'), ('deal_lost', 'Deal Lost'), ('ticket_update', 'Support Ticket Update'), ('system', 'System Notification')], default='system', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('icon', models.CharField(default='fa-bell', max_length=50)),
                ('color', models.CharField(default='blue', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
