# Generated by Django 5.2.17 on 2026-10-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_platformsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
