# Generated by Django 5.2.17 on 2026-10-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_supportticket_deleted_at_supportticket_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('proposal_sent', 'Proposal / RFQ Sent'), ('inquiry_reply', 'Inquiry Follow-up / Reply'), ('quote_received', 'Quote Recorded / Received'), ('status_changed', 'Stage Transition'), ('deal_won', 'Deal Won'), ('deal_lost', 'Deal Lost'), ('ticket_update', 'Support Ticket Update'), ('low_credits', 'Low Credits Warning'), ('credits_exhausted', 'Credits Exhausted'), ('plan_upgraded', 'Subscription Plan Updated'), ('payment_success', 'Payment Received'), ('invoice_generated', 'Invoice Generated'), ('system', 'System Notification')], default='system', max_length=30),
        ),
    ]
