# Generated by Django 5.2.17 on 2026-10-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerDashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_kpi_requirements', models.BooleanField(default=True)),
                ('show_kpi_searches', models.BooleanField(default=True)),
                ('show_kpi_suppliers_discovered', models.BooleanField(default=True)),
                ('show_kpi_saved_suppliers', models.BooleanField(default=True)),
                ('show_kpi_inquiries_sent', models.BooleanField(default=True)),
                ('show_kpi_credits', models.BooleanField(default=True)),
                ('show_quick_actions', models.BooleanField(default=True)),
                ('show_recent_searches', models.BooleanField(default=True)),
                ('show_recent_activity', models.BooleanField(default=True)),
                ('show_top_suppliers', models.BooleanField(default=True)),
                ('show_subscription_widget', models.BooleanField(default=True)),
                ('kpi_refresh_rate', models.IntegerField(default=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Buyer Dashboard Layout',
                'verbose_name_plural': 'Buyer Dashboard Layouts',
            },
        ),
        migrations.CreateModel(
            name='BuyerModuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(max_length=60, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('nav_label', models.CharField(blank=True, max_length=100)),
                ('url_name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(default='fa-circle', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('requires_credits', models.BooleanField(default=False)),
                ('min_plan', models.CharField(choices=[('FREE', 'Free Tier'), ('PRO', 'Pro Tier'), ('ENTERPRISE', 'Enterprise Tier')], default='FREE', max_length=20)),
                ('is_visible_on_sidebar', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Buyer Module Configuration',
                'verbose_name_plural': 'Buyer Module Configurations',
                'ordering': ['order', 'id'],
            },
        ),
    ]
