# Generated by Django 5.2.17 on 2026-10-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_buyerdashboardlayout_buyermoduleconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='BothDashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_active_view', models.CharField(choices=[('combined', 'Combined Executive Overview'), ('buyer', 'Buyer Procurement View'), ('seller', 'Seller Sales View')], default='combined', max_length=20)),
                ('show_view_switcher', models.BooleanField(default=True)),
                ('show_combined_metrics', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Both Dashboard Layout',
                'verbose_name_plural': 'Both Dashboard Layouts',
            },
        ),
        migrations.CreateModel(
            name='SellerDashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_kpi_products', models.BooleanField(default=True)),
                ('show_kpi_searches', models.BooleanField(default=True)),
                ('show_kpi_leads_discovered', models.BooleanField(default=True)),
                ('show_kpi_saved_leads', models.BooleanField(default=True)),
                ('show_kpi_inquiries_received', models.BooleanField(default=True)),
                ('show_kpi_credits', models.BooleanField(default=True)),
                ('show_quick_actions', models.BooleanField(default=True)),
                ('show_recent_searches', models.BooleanField(default=True)),
                ('show_recent_activity', models.BooleanField(default=True)),
                ('show_top_leads', models.BooleanField(default=True)),
                ('show_subscription_widget', models.BooleanField(default=True)),
                ('kpi_refresh_rate', models.IntegerField(default=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seller Dashboard Layout',
                'verbose_name_plural': 'Seller Dashboard Layouts',
            },
        ),
        migrations.CreateModel(
            name='SellerModuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(max_length=60, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('nav_label', models.CharField(blank=True, max_length=100)),
                ('url_name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(default='fa-circle', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('requires_credits', models.BooleanField(default=False)),
                ('min_plan', models.CharField(choices=[('FREE', 'Free Tier'), ('PRO', 'Pro Tier'), ('ENTERPRISE', 'Enterprise Tier')], default='FREE', max_length=20)),
                ('is_visible_on_sidebar', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seller Module Configuration',
                'verbose_name_plural': 'Seller Module Configurations',
                'ordering': ['order', 'id'],
            },
        ),
    ]
