# Generated by Django 5.2.17 on 2026-10-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_bothdashboardlayout_sellerdashboardlayout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bothdashboardlayout',
            name='default_active_view',
            field=models.CharField(choices=[('combined', 'Combined Overview'), ('buyer', 'Buyer Procurement'), ('seller', 'Seller Sales')], default='combined', max_length=20),
        ),
    ]
