# Generated by Django 5.2.17 on 2026-10-03 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_about_company_address_line1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='companymember',
            name='unique_company_user',
        ),
        migrations.AddConstraint(
            model_name='companymember',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_one_company'),
        ),
    ]
