# Generated by Django 5.2.17 on 2026-10-03 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_companymember_unique_company_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
                ('permission', models.CharField(choices=[('READ', 'Read'), ('EDIT', 'Edit'), ('DELETE', 'Delete'), ('UPDATE', 'Update'), ('IMPORT', 'Import'), ('EXPORT', 'Export')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MemberPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='companymember',
            name='unique_user_one_company',
        ),
        migrations.AlterField(
            model_name='companymember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='companypermission',
            constraint=models.UniqueConstraint(fields=('module', 'permission'), name='unique_module_permission'),
        ),
        migrations.AddField(
            model_name='memberpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_assignments', to='companies.companymember'),
        ),
        migrations.AddField(
            model_name='memberpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_assignments', to='companies.companypermission'),
        ),
        migrations.AddConstraint(
            model_name='memberpermission',
            constraint=models.UniqueConstraint(fields=('member', 'permission'), name='unique_member_permission'),
        ),
    ]
