# Generated by Django 5.2.17 on 2026-10-03 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_companypermission_memberpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('endpoint', models.CharField(max_length=255)),
                ('status_code', models.IntegerField(default=200)),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('supplier', 'Supplier'), ('lead', 'Lead')], default='supplier', max_length=20)),
                ('product_title', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_currency', models.CharField(blank=True, default='USD', max_length=3)),
                ('price_converted', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_unit', models.CharField(blank=True, max_length=30)),
                ('moq', models.CharField(blank=True, max_length=50)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_global_cheaper', models.BooleanField(default=False)),
                ('savings_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('match_score', models.PositiveSmallIntegerField(default=0)),
                ('match_reason', models.TextField(blank=True)),
                ('need_signal', models.TextField(blank=True)),
                ('source_url', models.CharField(blank=True, max_length=500)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=150)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('company_role', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('supplier', 'Supplier'), ('trader', 'Trader'), ('exporter', 'Exporter'), ('distributor', 'Distributor'), ('end_user', 'End User')], default='supplier', max_length=30)),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('source_urls', models.JSONField(blank=True, default=list)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'External companies',
                'indexes': [models.Index(fields=['domain'], name='ai_search_e_domain_61a3e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('find_suppliers', 'Find Suppliers'), ('find_buyers', 'Find Buyers')], default='find_suppliers', max_length=20)),
                ('search_query', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('total_results', models.IntegerField(default=0)),
                ('queries_used', models.JSONField(blank=True, default=list)),
                ('tokens_used', models.IntegerField(default=0)),
                ('api_cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_jobs', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
