# Generated by Django 5.2.17 on 2026-10-03 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_search', '0002_initial'),
        ('requirements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='searchjob',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_jobs', to='requirements.requirement'),
        ),
        migrations.AddField(
            model_name='searchjob',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apilog',
            name='search_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to='ai_search.searchjob'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='external_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='ai_search.externalcompany'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='search_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ai_search.searchjob'),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['search_job', 'match_score'], name='ai_search_s_search__185737_idx'),
        ),
    ]
