# Generated by Django 5.2.17 on 2026-10-07 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_search', '0003_initial'),
        ('companies', '0005_companyrole_companymember_custom_role_rolepermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('parameter_key', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('criteria_value', models.CharField(blank=True, max_length=255)),
                ('rule_type', models.CharField(choices=[('weighted', 'Weighted (Percentage Contribution)'), ('mandatory', 'Mandatory (Must Satisfy)'), ('bonus', 'Bonus (Boost Points)')], default='weighted', max_length=20)),
                ('weight_percentage', models.PositiveSmallIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_parameters', to='companies.company')),
            ],
            options={
                'verbose_name': 'Matching Parameter',
                'verbose_name_plural': 'Matching Parameters',
                'ordering': ['-is_active', '-weight_percentage', 'id'],
            },
        ),
    ]
