# Generated by Django 5.2.17 on 2026-10-09 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_search', '0004_matchingparameter'),
        ('catalog', '0003_product_sku'),
        ('companies', '0006_company_deleted_at_company_is_deleted'),
        ('requirements', '0002_requirement_deleted_at_requirement_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='externalcompany',
            index=models.Index(fields=['name'], name='ai_search_e_name_d862a0_idx'),
        ),
        migrations.AddIndex(
            model_name='externalcompany',
            index=models.Index(fields=['company_role'], name='ai_search_e_company_afee02_idx'),
        ),
        migrations.AddIndex(
            model_name='searchjob',
            index=models.Index(fields=['company', 'job_type', '-created_at'], name='ai_search_s_company_d471eb_idx'),
        ),
        migrations.AddIndex(
            model_name='searchjob',
            index=models.Index(fields=['status'], name='ai_search_s_status_cacfbd_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['search_job', 'result_type', '-match_score'], name='ai_search_s_search__762429_idx'),
        ),
    ]
