# Generated by Django 5.2.17 on 2026-10-09 07:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_search', '0004_matchingparameter'),
        ('billing', '0002_credittransaction_receipt_number'),
        ('companies', '0006_company_deleted_at_company_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique slug e.g. free, pro, enterprise', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime / Pay-as-you-go')], default='monthly', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('included_credits', models.PositiveIntegerField(default=500, help_text='Monthly search / AI credits included')),
                ('max_team_members', models.PositiveIntegerField(default=5)),
                ('max_products', models.PositiveIntegerField(default=50)),
                ('max_saved_vendors', models.PositiveIntegerField(default=100)),
                ('search_limit_monthly', models.PositiveIntegerField(default=500)),
                ('website_extraction_limit', models.PositiveIntegerField(default=500)),
                ('ai_matching_limit', models.PositiveIntegerField(default=500)),
                ('feature_access', models.JSONField(blank=True, default=dict, help_text="Feature flags e.g. {'export_pdf': True}")),
                ('trial_days', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.AlterModelOptions(
            name='credittransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Credit Transaction', 'verbose_name_plural': 'Credit Transactions'},
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='balance_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='feature_code',
            field=models.CharField(blank=True, default='vendor_discovery', max_length=50),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('reversed', 'Reversed / Refunded')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='credits',
            field=models.IntegerField(help_text='Positive for additions, negative for deductions'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('allocation', 'Subscription Allocation'), ('purchase', 'Credit Purchase'), ('deduction', 'Feature Usage Deduction'), ('refund', 'Failed Job Refund'), ('expiry', 'Credit Expiry'), ('adjustment', 'Admin Adjustment')], default='deduction', max_length=20),
        ),
        migrations.CreateModel(
            name='CompanyCreditWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_credits', models.PositiveIntegerField(default=0)),
                ('purchased_credits', models.PositiveIntegerField(default=0)),
                ('promotional_credits', models.PositiveIntegerField(default=0)),
                ('reserved_credits', models.PositiveIntegerField(default=0)),
                ('credits_consumed', models.PositiveIntegerField(default=0)),
                ('last_reloaded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_wallet', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company Credit Wallet',
                'verbose_name_plural': 'Company Credit Wallets',
            },
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.companycreditwallet'),
        ),
        migrations.CreateModel(
            name='FeatureCreditCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_code', models.CharField(help_text='System code e.g. vendor_discovery, ai_matching', max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('credit_cost', models.PositiveIntegerField(default=1)),
                ('charging_unit', models.CharField(choices=[('per_job', 'Per Search Job'), ('per_website', 'Per Processed Website'), ('per_company', 'Per Matched Company'), ('per_op', 'Per Operation / Export')], default='per_job', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_cost_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Credit Cost',
                'verbose_name_plural': 'Feature Credit Costs',
                'ordering': ['feature_code'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('provider', models.CharField(default='Development Gateway / Manual Approval', max_length=50)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='success', max_length=20)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='companies.company')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.subscription')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid'), ('void', 'Void'), ('overdue', 'Overdue')], default='paid', max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='companies.company')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.subscription')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='billing.payment')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_code', models.CharField(max_length=50)),
                ('usage_quantity', models.PositiveIntegerField(default=1)),
                ('credits_charged', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('reserved', 'Credits Reserved'), ('completed', 'Successfully Processed'), ('failed', 'Processing Failed'), ('refunded', 'Credits Refunded')], default='completed', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='companies.company')),
                ('search_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='ai_search.searchjob')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Record',
                'verbose_name_plural': 'Usage Records',
                'ordering': ['-started_at'],
            },
        ),
    ]
