# Generated by Django 5.2.17 on 2026-10-09 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_search', '0005_externalcompany_ai_search_e_name_d862a0_idx_and_more'),
        ('billing', '0003_subscriptionplan_alter_credittransaction_options_and_more'),
        ('companies', '0006_company_deleted_at_company_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('allocation', 'Subscription Allocation'), ('purchase', 'Credit Purchase'), ('deduction', 'Feature Usage Deduction'), ('refund', 'Failed Job Refund'), ('expiry', 'Credit Expiry'), ('adjustment', 'Admin Adjustment'), ('credit', 'Credit'), ('debit', 'Debit')], default='deduction', max_length=20),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['company', '-created_at'], name='billing_cre_company_af3c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['company', 'transaction_type'], name='billing_cre_company_cfc6cb_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['receipt_number'], name='billing_cre_receipt_80fba9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'status', '-created_at'], name='billing_inv_company_9e52c8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='billing_inv_invoice_70511c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'status', '-created_at'], name='billing_pay_company_c47b27_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider_reference'], name='billing_pay_provide_f758e1_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['company', '-started_at'], name='billing_usa_company_c6cba2_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['company', 'user', '-started_at'], name='billing_usa_company_fb804b_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['feature_code', 'status'], name='billing_usa_feature_1402ee_idx'),
        ),
    ]
