# Generated by Django 5.2.17 on 2026-10-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_credittransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='expiry_warning_5d_sent',
            field=models.BooleanField(default=False),
        ),
    ]
