# Generated by Django 5.2.17 on 2026-10-07 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='delivery_terms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='quoted_currency',
            field=models.CharField(blank=True, default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='quoted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('in_discussion', 'In Discussion'), ('replied', 'Replied / Quoted'), ('won', 'Accepted / Won'), ('lost', 'Lost / Closed'), ('failed', 'Failed')], default='sent', max_length=20),
        ),
        migrations.CreateModel(
            name='InquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=150)),
                ('message_type', models.CharField(choices=[('outbound', 'Outbound (Sent by Us)'), ('inbound', 'Inbound (Counterparty Response)'), ('system', 'System Event')], default='outbound', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='leads.inquiry')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
