# Generated by Django 5.2.17 on 2026-10-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_inquiry_delivery_terms_inquiry_quoted_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional Quotation PDF, Technical Specs, or RFQ Document', null=True, upload_to='inquiries/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='attachment_name',
            field=models.CharField(blank=True, help_text='Original filename of the attached document', max_length=255),
        ),
        migrations.AddField(
            model_name='inquirymessage',
            name='attachment',
            field=models.FileField(blank=True, help_text='Attached commercial document or specification', null=True, upload_to='inquiry_messages/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='inquirymessage',
            name='attachment_name',
            field=models.CharField(blank=True, help_text='Original filename of the attached document', max_length=255),
        ),
    ]
