# Generated by Django 5.2.17 on 2026-10-09 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_search', '0005_externalcompany_ai_search_e_name_d862a0_idx_and_more'),
        ('companies', '0006_company_deleted_at_company_is_deleted'),
        ('leads', '0004_alter_inquiry_search_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['company', 'status', '-sent_at'], name='leads_inqui_company_370072_idx'),
        ),
        migrations.AddIndex(
            model_name='saveditem',
            index=models.Index(fields=['company', 'status', '-created_at'], name='leads_saved_company_65f38a_idx'),
        ),
    ]
