# Generated by Django 5.2.17 on 2026-10-03 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('companies', '0004_companypermission_memberpermission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('specifications', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=14)),
                ('unit', models.CharField(default='pcs', max_length=30)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('delivery_city', models.CharField(blank=True, max_length=100)),
                ('delivery_country', models.CharField(default='India', max_length=100)),
                ('required_by', models.DateField(blank=True, null=True)),
                ('search_scope', models.CharField(choices=[('nearby', 'Nearby'), ('country', 'Country'), ('global', 'Global')], default='global', max_length=20)),
                ('radius_km', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('searching', 'Searching'), ('completed', 'Completed'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='catalog.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='requirement_company_20cf8a_idx')],
            },
        ),
    ]
