# Generated by Django 5.2.17 on 2026-10-06 04:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_availability_product_created_by_and_more'),
        ('companies', '0004_companypermission_memberpermission_and_more'),
        ('requirements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['company', 'is_deleted'], name='requirement_company_1d58c2_idx'),
        ),
    ]
