# Generated by Django 5.2.17 on 2026-10-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_availability_product_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Stock Keeping Unit or internal Catalog/Part Code', max_length=100),
        ),
    ]
